import { Link } from 'react-router-dom';

/**
 * Terms of service for Biblefuel Studio. Linked from the landing footer and
 * registered as the "Application Terms of Service link" on the Google Auth
 * Platform consent screen — Google requires a reachable ToS URL before an app
 * using sensitive YouTube scopes can pass verification.
 *
 * The YouTube section is not boilerplate: the YouTube API Services Terms
 * require any app using the API to bind its users to YouTube's own terms and
 * to surface Google's privacy policy. Do not drop it.
 *
 * Not legal advice — operators running this in production should have it
 * reviewed against their local jurisdiction.
 */
export function TermsPage() {
    return (
        <div className="min-h-screen bg-editorial-paper text-editorial-body">
            <div className="mx-auto max-w-2xl px-5 py-12 sm:px-8 sm:py-20">
                <Link to="/" className="font-sans text-[11px] uppercase tracking-[1.5px] text-editorial-muted hover:text-editorial-ink">
                    ← Back
                </Link>

                <h1 className="mt-6 font-displaySerif text-3xl text-editorial-ink sm:text-4xl">
                    Terms of service
                </h1>
                <p className="mt-2 text-[12px] text-editorial-muted">Last updated: 2026-09-23</p>

                <section className="mt-10 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">What Biblefuel is</h2>
                    <p>
                        Biblefuel Studio is a tool for producing scripture-based videos: you write or generate a script, we synthesise narration, assemble visuals, and render a video file you can download or publish. Using the service means you accept these terms.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Your account</h2>
                    <p>
                        You need an account to use the studio, and you must be old enough to form a binding contract where you live. Keep your sign-in details to yourself — anything done through your account is treated as done by you. One person or organisation per account; don't share logins.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Your work stays yours</h2>
                    <p>
                        You own the scripts you write, the audio we generate for you, and the videos you render. We claim no ownership and no right to publish, resell, or train on your work. We process it only to run the service for you — storing it, rendering it, and delivering it back.
                    </p>
                    <p>
                        You are responsible for holding the rights to anything you upload: images, music, voice recordings. If you upload a track you don't have a licence for, that is your exposure, not ours.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Scripture text</h2>
                    <p>
                        Verse text is retrieved verbatim from third-party Bible APIs and is never paraphrased or generated by a language model. Public-domain translations such as the King James Version carry no restriction. Modern translations remain the copyright of their publishers, and quoting them at length in a published video is your responsibility to clear.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Publishing to YouTube</h2>
                    <p>
                        Biblefuel uses YouTube API Services to upload videos to a channel you connect. By connecting a channel you also agree to the{' '}
                        <a href="https://www.youtube.com/t/terms" className="underline" target="_blank" rel="noreferrer">YouTube Terms of Service</a>, and you accept that Google's use of information it receives is governed by the{' '}
                        <a href="https://policies.google.com/privacy" className="underline" target="_blank" rel="noreferrer">Google Privacy Policy</a>.
                    </p>
                    <p>
                        We request only the permissions needed to upload a video and read your channel name. We never post without an explicit action from you. You can revoke our access at any time from your{' '}
                        <a href="https://myaccount.google.com/permissions" className="underline" target="_blank" rel="noreferrer">Google account permissions</a> page, or by disconnecting from Settings — which deletes the stored token from our servers.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Acceptable use</h2>
                    <p>Don't use Biblefuel to produce or distribute:</p>
                    <ul className="ml-5 list-disc space-y-2">
                        <li>material that infringes someone else's copyright or trademark;</li>
                        <li>content that harasses, defames, or incites violence against any person or group;</li>
                        <li>sexual content involving minors, or any other material unlawful where you are;</li>
                        <li>impersonations of a real person, church, or organisation presented as genuine.</li>
                    </ul>
                    <p>
                        Don't attempt to break, overload, or reverse-engineer the service, and don't resell access to it. We may suspend an account that does.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Plans and payment</h2>
                    <p>
                        Free accounts carry daily limits on scripts, narration, renders, and image generation. Paid plans are billed through Stripe on a recurring basis until cancelled; cancel any time from Settings and you keep access until the end of the period you have paid for. We don't refund part-used periods unless the law where you live says otherwise.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Availability and limits</h2>
                    <p>
                        The service is provided as is. We don't promise uninterrupted availability, and rendering depends on third-party providers for speech, images, and scripture text that can fail or change. Keep your own copies of anything you care about — we are not a backup service.
                    </p>
                    <p>
                        To the extent the law allows, our total liability to you for any claim is limited to what you paid us in the twelve months before it arose. Nothing here limits liability for death, personal injury, or fraud.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Ending it</h2>
                    <p>
                        You can delete your account whenever you like from <Link to="/app/settings" className="underline">Settings → Danger zone</Link>, which wipes your data directory. We may close an account that breaches these terms, and we will tell you why unless we are legally barred from doing so.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Changes</h2>
                    <p>
                        We may update these terms as the service changes. The date at the top always reflects the current version; material changes will be notified by email to the address on your account.
                    </p>
                </section>

                <section className="mt-8 space-y-4 font-bodyserif text-[15px] leading-relaxed">
                    <h2 className="font-displaySerif text-xl text-editorial-ink">Operator and law</h2>
                    <p>
                        Biblefuel is operated by Tiwaton LTD, registered in the UK. These terms are governed by the law of England and Wales, and its courts have exclusive jurisdiction. Questions:{' '}
                        <a href="mailto:hello@tiwaton.co.uk" className="underline">hello@tiwaton.co.uk</a>.
                    </p>
                    <p>
                        See also our <Link to="/privacy" className="underline">privacy notice</Link>.
                    </p>
                </section>

                <div className="mt-12">
                    <Link
                        to="/"
                        className="inline-block rounded-sm bg-editorial-ink px-5 py-3 font-sans text-[11px] font-medium uppercase tracking-[1.6px] text-editorial-paper"
                    >
                        Back to landing
                    </Link>
                </div>
            </div>
        </div>
    );
}
